name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      env:
        EML_ENV: ${{ secrets.EML_ENV }}
        GFB_ENV: ${{ secrets.GFB_ENV }}        
        GPR_ENV: ${{ secrets.GPR_ENV }}
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future" 
        find . -type f -name "*.js" -exec sed -i 's/EML_ENV/${{ secrets.EML_ENV }}/g' {} + 
        find . -type f -name "*.js" -exec sed -i 's/GFB_ENV/${{ secrets.GFB_ENV }} /g' {} +
        find . -type f -name "*.js" -exec sed -i 's/GPR_ENV/${{ secrets.GPR_ENV }}/g' {} +
        
